name: hswitch
version: "VERSION-STRING"
summary: hosts file content switcher to modify your static ip addresses
grade: stable
confinement: strict
description: |
  hswitch is a hosts file content switcher to modify your static ip addresses 
  quickly for development.
  https://github.com/pbek/hswitch

apps:
  hswitch:
    command: desktop-launch ${SNAP}/usr/bin/hswitch --snap
    # see https://developer.ubuntu.com/en/snappy/guides/interfaces
    plugs:
      - x11
      - unity7
      - home

parts:
  hswitch:
    source: https://github.com/pbek/hswitch.git
    plugin: qmake
    qt-version: qt5
    source-branch: develop
    options:
       - ./src
       - CONFIG+=release
    build-packages:
      - qttools5-dev
      - build-essential
      - libqt5svg5-dev
      - qttools5-dev-tools
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libqt5svg5
    stage:
      - -usr/share/pkgconfig
    after: [desktop-qt5]
